#!/bin/zsh

SCRIPTPATH=$0:A:h
F="$SCRIPTPATH/files"

function setpath(){
    set -e
    set -x
    (cd "$F" && "$1" "$@")
}

function files(){
    install bash-lsp.lua        ~/.config/nvim/lua/
    install python-lsp.lua      ~/.config/nvim/lua/
    install clang-lsp.lua       ~/.config/nvim/lua/
    install compe-config.lua    ~/.config/nvim/lua/
    install init.vim            ~/.config/nvim/
    install lsp-config.vim      ~/.config/nvim/
    install .vimrc              ~/
    install .bashrc             ~/
    install .zshrc              ~/
}

function apps(){
    npm config set prefix "$HOME/.npm-packages"
    npm i -g pyright
    npm i -g bash-language-server
    npm i -g vim-language-server
    npm i -g clangd
    GO111MODULE=on go get golang.org/x/tools/gopls@latest
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

function dir(){
    mkdir -p ~/.config/nvim/plugged
    mkdir -p ~/.config/nvim/lua
    mkdir -p ~/.vim
    echo $NPM_PACKAGES/bin
    mkdir -p $NPM_PACKAGES/bin # from .zshrc
}

function __push(){
    dir
    apps
    files
    nvim +PlugInstall
}

function __pull(){
    install ~/.config/nvim/*.vim .
    install ~/.config/nvim/lua/*.lua .
    install ~/.vimrc .
    install ~/.zshrc .
    install ~/.bashrc .
}

function __git(){
    "$@"
}

([ "$1" = push ] || [ "$1" = pull ]) && setpath "__$1" && exit 0

# Convencient way to interact with git repo regardless of cwd
[ "$1" = git ] && setpath "__$1" "$@" && exit 0

echo
echo "usage: $0 [push|pull]"
echo
echo "push/pull registered files between a git repo and filesystem locations"
echo
echo "push      - deploy files from vcs directory and install deps"
echo "pull      - move files to vcs directory"
echo "git       - run vcs commands"
echo
