#!/bin/zsh

set -e

SCRIPTPATH=$0:A:h
F="$SCRIPTPATH/files"

function check_dep(){
	for cmd in "$@"; do
		if ! command -v $cmd > /dev/null; then
			echo "command [$cmd] not be found"
			exit
		fi
	done
}


function setpath(){
    set -e
    set -x
    (cd "$F" && "$1" "$@")
}

function files(){
    install lsp-keybinds.lua    ~/.config/nvim/lua/plugged
    install init.vim            ~/.config/nvim/
    install -t ~/.config/nvim/lua/plugins lsp-keybinds.lua  nvim-cmp.lua  nvim-web-devicons.lua  plugins.lua  telescope.lua  trouble.lua
    install .vimrc              ~/
    install .ctags              ~/
    install .bashrc             ~/
    install .zshrc              ~/
    install .muttrc             ~/
    install .gitconfig          ~/
    install efm-langserver.yaml ~/.config/efm-langserver/config.yaml
    gmail-yaml-filters gmail-filters.yml > ~/Downloads/myfilters.xml #manually imported
}

function apps(){
    npm config set prefix "$HOME/.npm-packages"
    npm i -g pyright
    npm i -g bash-language-server
    npm i -g vim-language-server
    npm i -g clangd
    pip install gmail-yaml-filters
    GO111MODULE=on go get golang.org/x/tools/gopls@latest
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    zsh -c "git clone git@github.com/zsh-users/zsh-autosuggestions.git ~/.config/zsh/plugins/zsh-autosuggestions"
    zsh -c "git clone git@github.com:olivierverdier/zsh-git-prompt.git ~/.config/zsh/zsh-git-prompt/zsh-git-prompt"
}

function dir(){
    mkdir -p ~/.config/nvim/plugged/
    mkdir -p ~/.config/nvim/lua/plugins/
    mkdir -p ~/.config/nvim/lua/
    mkdir -p ~/.config/zsh/zsh-git-prompt
    mkdir -p ~/.config/efm-langserver
    mkdir -p ~/.vim/autoload/
    mkdir -p ~/.mutt/cache
    echo $NPM_PACKAGES/bin
    mkdir -p $NPM_PACKAGES/bin # from .zshrc
}

function __push(){
    dir
    files
}

function __install(){
    dir
    apps
    files
    nvim +PlugInstall
}

function __pull(){
    install ~/.config/nvim/*.vim .
    install ~/.config/nvim/lua/plugins/* .
    install ~/.vimrc .
    install ~/.muttrc .
    install ~/.zshrc .
    install ~/.bashrc .
    install ~/.ctags .
    install ~/.gitconfig .
    install ~/.config/efm-langserver/ ./efm-langserver.yaml
}

function __git(){
    "$@"
}

check_dep install zsh curl pip npm go vgrep

([ "$1" = push ] || [ "$1" = pull ] || [ "$1" = install ]) && setpath "__$1" && exit 0

# Convenient way to interact with git repo regardless of cwd
[ "$1" = git ] && setpath "__$1" "$@" && exit 0

echo
echo "usage: $0 [push|pull|install|git]"
echo
echo "push/pull registered files between a git repo and filesystem locations"
echo
echo "git <cmd> - run vcs commands as cwd is in the repo directory"
echo "install   - deploy files from vcs directory and install deps"
echo "push      - deploy files from vcs directory"
echo "pull      - move files to vcs directory"
echo
